// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum_example.proto

package com.jack.protobuf;

public final class EnumExample {
  private EnumExample() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code com.jack.protobuf.DayOfWeek}
   */
  public enum DayOfWeek
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>UNKNOWN = 0;</code>
     */
    UNKNOWN(0),
    /**
     * <code>MONDAY = 1;</code>
     */
    MONDAY(1),
    /**
     * <code>TUESDAY = 2;</code>
     */
    TUESDAY(2),
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    WEDNESDAY(3),
    /**
     * <code>THURSDAY = 4;</code>
     */
    THURSDAY(4),
    /**
     * <code>FRIDAY = 5;</code>
     */
    FRIDAY(5),
    /**
     * <code>SATURDAY = 6;</code>
     */
    SATURDAY(6),
    /**
     * <code>SUNDAY = 7;</code>
     */
    SUNDAY(7),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>UNKNOWN = 0;</code>
     */
    public static final int UNKNOWN_VALUE = 0;
    /**
     * <code>MONDAY = 1;</code>
     */
    public static final int MONDAY_VALUE = 1;
    /**
     * <code>TUESDAY = 2;</code>
     */
    public static final int TUESDAY_VALUE = 2;
    /**
     * <code>WEDNESDAY = 3;</code>
     */
    public static final int WEDNESDAY_VALUE = 3;
    /**
     * <code>THURSDAY = 4;</code>
     */
    public static final int THURSDAY_VALUE = 4;
    /**
     * <code>FRIDAY = 5;</code>
     */
    public static final int FRIDAY_VALUE = 5;
    /**
     * <code>SATURDAY = 6;</code>
     */
    public static final int SATURDAY_VALUE = 6;
    /**
     * <code>SUNDAY = 7;</code>
     */
    public static final int SUNDAY_VALUE = 7;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static DayOfWeek valueOf(int value) {
      return forNumber(value);
    }

    public static DayOfWeek forNumber(int value) {
      switch (value) {
        case 0: return UNKNOWN;
        case 1: return MONDAY;
        case 2: return TUESDAY;
        case 3: return WEDNESDAY;
        case 4: return THURSDAY;
        case 5: return FRIDAY;
        case 6: return SATURDAY;
        case 7: return SUNDAY;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        DayOfWeek> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<DayOfWeek>() {
            public DayOfWeek findValueByNumber(int number) {
              return DayOfWeek.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.jack.protobuf.EnumExample.getDescriptor().getEnumTypes().get(0);
    }

    private static final DayOfWeek[] VALUES = values();

    public static DayOfWeek valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private DayOfWeek(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:com.jack.protobuf.DayOfWeek)
  }

  public interface EnumMessageOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.jack.protobuf.EnumMessage)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     */
    int getId();

    /**
     * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
     */
    int getDayOfWeekValue();
    /**
     * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
     */
    com.jack.protobuf.EnumExample.DayOfWeek getDayOfWeek();
  }
  /**
   * Protobuf type {@code com.jack.protobuf.EnumMessage}
   */
  public  static final class EnumMessage extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.jack.protobuf.EnumMessage)
      EnumMessageOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use EnumMessage.newBuilder() to construct.
    private EnumMessage(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private EnumMessage() {
      id_ = 0;
      dayOfWeek_ = 0;
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private EnumMessage(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownFieldProto3(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {

              id_ = input.readInt32();
              break;
            }
            case 16: {
              int rawValue = input.readEnum();

              dayOfWeek_ = rawValue;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.jack.protobuf.EnumExample.internal_static_com_jack_protobuf_EnumMessage_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.jack.protobuf.EnumExample.internal_static_com_jack_protobuf_EnumMessage_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.jack.protobuf.EnumExample.EnumMessage.class, com.jack.protobuf.EnumExample.EnumMessage.Builder.class);
    }

    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     */
    public int getId() {
      return id_;
    }

    public static final int DAY_OF_WEEK_FIELD_NUMBER = 2;
    private int dayOfWeek_;
    /**
     * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
     */
    public int getDayOfWeekValue() {
      return dayOfWeek_;
    }
    /**
     * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
     */
    public com.jack.protobuf.EnumExample.DayOfWeek getDayOfWeek() {
      com.jack.protobuf.EnumExample.DayOfWeek result = com.jack.protobuf.EnumExample.DayOfWeek.valueOf(dayOfWeek_);
      return result == null ? com.jack.protobuf.EnumExample.DayOfWeek.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (id_ != 0) {
        output.writeInt32(1, id_);
      }
      if (dayOfWeek_ != com.jack.protobuf.EnumExample.DayOfWeek.UNKNOWN.getNumber()) {
        output.writeEnum(2, dayOfWeek_);
      }
      unknownFields.writeTo(output);
    }

    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (id_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, id_);
      }
      if (dayOfWeek_ != com.jack.protobuf.EnumExample.DayOfWeek.UNKNOWN.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(2, dayOfWeek_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.jack.protobuf.EnumExample.EnumMessage)) {
        return super.equals(obj);
      }
      com.jack.protobuf.EnumExample.EnumMessage other = (com.jack.protobuf.EnumExample.EnumMessage) obj;

      boolean result = true;
      result = result && (getId()
          == other.getId());
      result = result && dayOfWeek_ == other.dayOfWeek_;
      result = result && unknownFields.equals(other.unknownFields);
      return result;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId();
      hash = (37 * hash) + DAY_OF_WEEK_FIELD_NUMBER;
      hash = (53 * hash) + dayOfWeek_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.jack.protobuf.EnumExample.EnumMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.jack.protobuf.EnumExample.EnumMessage prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.jack.protobuf.EnumMessage}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.jack.protobuf.EnumMessage)
        com.jack.protobuf.EnumExample.EnumMessageOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.jack.protobuf.EnumExample.internal_static_com_jack_protobuf_EnumMessage_descriptor;
      }

      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.jack.protobuf.EnumExample.internal_static_com_jack_protobuf_EnumMessage_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.jack.protobuf.EnumExample.EnumMessage.class, com.jack.protobuf.EnumExample.EnumMessage.Builder.class);
      }

      // Construct using com.jack.protobuf.EnumExample.EnumMessage.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      public Builder clear() {
        super.clear();
        id_ = 0;

        dayOfWeek_ = 0;

        return this;
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.jack.protobuf.EnumExample.internal_static_com_jack_protobuf_EnumMessage_descriptor;
      }

      public com.jack.protobuf.EnumExample.EnumMessage getDefaultInstanceForType() {
        return com.jack.protobuf.EnumExample.EnumMessage.getDefaultInstance();
      }

      public com.jack.protobuf.EnumExample.EnumMessage build() {
        com.jack.protobuf.EnumExample.EnumMessage result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.jack.protobuf.EnumExample.EnumMessage buildPartial() {
        com.jack.protobuf.EnumExample.EnumMessage result = new com.jack.protobuf.EnumExample.EnumMessage(this);
        result.id_ = id_;
        result.dayOfWeek_ = dayOfWeek_;
        onBuilt();
        return result;
      }

      public Builder clone() {
        return (Builder) super.clone();
      }
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.setField(field, value);
      }
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return (Builder) super.clearField(field);
      }
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return (Builder) super.clearOneof(oneof);
      }
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return (Builder) super.setRepeatedField(field, index, value);
      }
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return (Builder) super.addRepeatedField(field, value);
      }
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.jack.protobuf.EnumExample.EnumMessage) {
          return mergeFrom((com.jack.protobuf.EnumExample.EnumMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.jack.protobuf.EnumExample.EnumMessage other) {
        if (other == com.jack.protobuf.EnumExample.EnumMessage.getDefaultInstance()) return this;
        if (other.getId() != 0) {
          setId(other.getId());
        }
        if (other.dayOfWeek_ != 0) {
          setDayOfWeekValue(other.getDayOfWeekValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      public final boolean isInitialized() {
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.jack.protobuf.EnumExample.EnumMessage parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.jack.protobuf.EnumExample.EnumMessage) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int id_ ;
      /**
       * <code>int32 id = 1;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder setId(int value) {
        
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       */
      public Builder clearId() {
        
        id_ = 0;
        onChanged();
        return this;
      }

      private int dayOfWeek_ = 0;
      /**
       * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
       */
      public int getDayOfWeekValue() {
        return dayOfWeek_;
      }
      /**
       * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
       */
      public Builder setDayOfWeekValue(int value) {
        dayOfWeek_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
       */
      public com.jack.protobuf.EnumExample.DayOfWeek getDayOfWeek() {
        com.jack.protobuf.EnumExample.DayOfWeek result = com.jack.protobuf.EnumExample.DayOfWeek.valueOf(dayOfWeek_);
        return result == null ? com.jack.protobuf.EnumExample.DayOfWeek.UNRECOGNIZED : result;
      }
      /**
       * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
       */
      public Builder setDayOfWeek(com.jack.protobuf.EnumExample.DayOfWeek value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        dayOfWeek_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.com.jack.protobuf.DayOfWeek day_of_week = 2;</code>
       */
      public Builder clearDayOfWeek() {
        
        dayOfWeek_ = 0;
        onChanged();
        return this;
      }
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFieldsProto3(unknownFields);
      }

      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.jack.protobuf.EnumMessage)
    }

    // @@protoc_insertion_point(class_scope:com.jack.protobuf.EnumMessage)
    private static final com.jack.protobuf.EnumExample.EnumMessage DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.jack.protobuf.EnumExample.EnumMessage();
    }

    public static com.jack.protobuf.EnumExample.EnumMessage getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<EnumMessage>
        PARSER = new com.google.protobuf.AbstractParser<EnumMessage>() {
      public EnumMessage parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new EnumMessage(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<EnumMessage> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<EnumMessage> getParserForType() {
      return PARSER;
    }

    public com.jack.protobuf.EnumExample.EnumMessage getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_jack_protobuf_EnumMessage_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_jack_protobuf_EnumMessage_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022enum_example.proto\022\021com.jack.protobuf\"" +
      "L\n\013EnumMessage\022\n\n\002id\030\001 \001(\005\0221\n\013day_of_wee" +
      "k\030\002 \001(\0162\034.com.jack.protobuf.DayOfWeek*t\n" +
      "\tDayOfWeek\022\013\n\007UNKNOWN\020\000\022\n\n\006MONDAY\020\001\022\013\n\007T" +
      "UESDAY\020\002\022\r\n\tWEDNESDAY\020\003\022\014\n\010THURSDAY\020\004\022\n\n" +
      "\006FRIDAY\020\005\022\014\n\010SATURDAY\020\006\022\n\n\006SUNDAY\020\007b\006pro" +
      "to3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_com_jack_protobuf_EnumMessage_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_jack_protobuf_EnumMessage_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_jack_protobuf_EnumMessage_descriptor,
        new java.lang.String[] { "Id", "DayOfWeek", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
